### ISSUE TITLE
edges not being drawn using motifs in a NetworkFrame

### ISSUE THREAD

**Issue by bengarvey** [emeeks/semiotic#104]
Trying to use motifs to place my nodes explicitly (I think that's what motifs are for, but not entirely sure). The nodes are placed correctly, but the links aren't. When I change it back to the force layout, the links are rendered fine.

```
    <ResponsiveNetworkFrame
        size={[ 300, 500 ]}
        responsiveWidth={true}
        edges={network.links}
        nodes={network.nodes}
        edgeStyle={(d) => ({ stroke: colors[d.relation], fill: colors[d.relation], opacity: 0.5, strokeWidth: '1px' })} 
        nodeStyle={d => ({ fill: colors[d.side], r:"15px", x:getAdjustedXY(d)[0], y:getAdjustedXY(d)[1] })} 
        networkType={{ type: 'motifs', iterations: 500, edgeStrength:0.07, multi:true }}
        edgeType={'arrowhead'}
        nodeSizeAccessor={d => 7}
        zoomToFit={true}
        nodeIDAccessor={"id"}
        hoverAnnotation={true}
        tooltipContent={d =>
        <div className="tooltip-content" >
          <p>{d.id}</p>
          <p>{d.name}</p>
          <p>Force Side: {d.side}</p>
        </div>}
        margin={{left: 20, top: 20, bottom: 20, right: 50}}
    /> 
```

Motif:
![screen shot 2017-12-02 at 2 18 44 pm](https://user-images.githubusercontent.com/1342331/33518999-11838aae-d76c-11e7-8391-e46ee7d3c7c1.png)

Mostly the same code, but force:
![screen shot 2017-12-02 at 2 21 57 pm](https://user-images.githubusercontent.com/1342331/33519013-3903f6fe-d76c-11e7-8c0d-c98ebbb92373.png)

**Comment by emeeks** [comment]
I pulled out `graphology` because it had a security issue and that broke `motifs` since I couldn't calculate components anymore. I just finished a simple BFS weak component function and included it in `1.3.0` which is just published. That said, it might not be that motifs is the mode you want. It splits each component of the graph into its own space, with singletons grouped together. I'm going to close this comment but feel free to reopen it or just otherwise talk through what you'd like to see with the network frame.
