### ISSUE TITLE
OrdinalFrame rendering issues after filtering

### ISSUE THREAD

**Issue by infograafikko** [emeeks/semiotic#175]
I am not sure if this is issue with Semiotic or my bootstrap. I am using this bootstrap: https://www.creative-tim.com/product/light-bootstrap-dashboard-react and OrdinalFrame doesn't render properly after filtering data.

I have made simple example to Codepen and it works just fine. https://codepen.io/Sokrates86/pen/yKeGbY

However if I implement the same graph, button and filtering with the bootstrap it doesn't rerender properly.

Screenshot: https://i.imgur.com/ccPllSy.png

Do you guys have any idea what could be wrong?

**Comment by netbek** [comment]
The provided CodePen looks OK to me. In your screenshot it looks like the transition is stuck at the first frame. Is that what you're seeing?

Would it be possible to provide a CodePen with your component inside the Bootstrap template? I'd be interested to see how you've implement state and event handlers, or whether everything is kept in the component, as in the example you provided.

Alternatively, maybe add `console.log` call at the start of your component's `render` method to see if it's being called repeatedly somehow because of props or state changes.

**Comment by emeeks** [comment]
Gonna close this and assume it was just a bootstrap thing.
