### ISSUE TITLE
Flat data array support / `accessor` props and docs clarification

### ISSUE THREAD

**Issue by mkascel** [emeeks/semiotic#189]
Regarding `lineDataAccessor` and it's related props, the docs say "*If*" you specify accessor props, they will be used, but these seem to be mandatory, not optional.  For instance, my data is already supplied to semiotic as a flat array, e.g. `[ {ts: 0, value: 1}, {ts: 1, value: 2} ]`.  I have to put it in a form like `{data: myDataArray}` and use `lineDataAccessor="data"`; is this by design or should this stay optional and flat arrays be supported?  Either way docs should be clarified regarding this (I'm happy to do this for this issue and issue I just filed before).

**Comment by emeeks** [comment]
Oh that's an interesting point and I hadn't thought about interpreting it that way, which now that I see it, I agree with the interpretation. The answer is no, by default lineDataAccessor is set to the equivalent of: `d => d.coordinates`. You could, conceivably, set it to `d => d` and use flat arrays but I'm not sure if that would have unintended consequences elsewhere. Please feel free to update the data and point me at the update and I will clarify. Or let me know if it's still unclear.

**Comment by mkascel** [comment]
I think this is more an API decision than anything else; in general to me it seems better for the default to be accepting the `data` as a flat array and allowing functionality for other data structures via the data accessor props vs pushing people toward a specific data structure from the beginning.  It seems this is just a decision that was made and I'm not sure of a good way off the top of my head to change this in a non-breaking way.

For me, and I assume for a lot of people coming from Redux, I have specific selectors that are returning my chart values as arrays of objects; I don't see the benefit of packing my data up into more complex structures.  But maybe this is because I'm not using the other features/concepts of your library (annotations, the different layers etc) so maybe for those who are using all of these features it makes sense to package up chart data in this way.  In general when people first approach the lib though, I at least thought "I want to just draw a chart in the simplest way possible" and to just provide the data and expect a line-chart to render but to get exceptions was kind of a head-scratcher as a newcomer.  For me it was a combination of 1) I was passing in immutable data, which just throws exceptions, and 2) I didn't know (or willfull disregarded the fact) that the lib expects data in the form of `{coordinates: []}`

**Comment by emeeks** [comment]
No I think that makes sense. It's a breaking change unfortunately, because of the earlier decision, and I can't think of a way to make it without going to 2.0.0 at which point I'd make a bunch of other changes, too. I can think of one minor-change approach which is if you send an array then it ignores the lineDataAccessor and just deals with the array as the data. Does that make sense?

**Comment by emeeks** [comment]
The next version will support you sending an array of arrays to `lines` or `areas`. It still has to be an array of arrays because I can't figure out a way to check to see if the array you're sending is a set of coordinates or an array of lines with coordinates. But now if you send:

`lines={[[{x: 5, y: 3}, {x: 8, y: 40}, {x:12, y:100}],[{x: 2, y: 5}, {x: 3, y 4}]]}` it will work.
