### ISSUE TITLE
Click interactivity issues

### ISSUE THREAD

**Issue by ZachHaber** [emeeks/semiotic#198]
I was looking into implementing custom click functionality, and I noticed some issues:
customDoubleclickBehavior doesn't work on all frame types. I was unable to get a double click event to be triggered. If the customClickBehavior was implemented, it was called twice instead of a double click event. Otherwise nothing happened when I tried double clicking.
The customClickBehavior isn't triggered when clicking on a sketchy ordinal frame mark (e.g. the bars in a bar graph).
The customClickBehavior also isn't triggered when hoverAnnotation isn't turned on for XY and Network frames, but it works when neither hoverAnnotation nor pieceHoverAnnotation are turned on for Ordinal frames.
If it would help with fixing that behavior, I can put together a codepen that has all of the different behaviors I mentioned.

I was also wondering if it'd be possible to either add a custom right click behavior (that would perform an action on right click rather than opening the right click context menu) or to add the ability to make my own right click context menu for the graph elements?

Sorry, there's a lot to this one. Once again, thanks for all of your hard work on this library!

**Comment by emeeks** [comment]
Okay this was a lot to dig through to get everything working the way it should but I think I've got it fixed:

* custom behaviors only work in OrdinalFrame when `hoverAnnotation` is set (you could set it to `hoverAnnotation={[]}` if you don't want any hover tooltips). The older settings were an undocumented feature that decorated the actual shapes, which is not an approach that Semiotic is designed to support.
* click, hover, and doubleclick all work in all the frames (including `pieceHoverAnnotation` and `hoverAnnotation` in `OrdinalFrame`.
* I'm not going to add a right-click behavior, it's generally considered bad practice in web applications because people expect the browser menu.

This will be in the next release which will hopefully come tomorrow.

**Comment by emeeks** [comment]
Fixed in 1.10.0
