### ISSUE TITLE
Graphs in tooltips

### ISSUE THREAD

**Issue by ZachHaber** [emeeks/semiotic#205]
I am working on a visualization where we are going to make relevant graphs on the tooltips of the graph nodes. You mentioned that this was possible in the documentation. I have some concerns with this that I'd like your help to figure out.
Would it be possible to make a tooltip stay up if the user brings the mouse onto the tooltip?
That leads into a second concern, would tooltips generated by graphs in a tooltip display properly?
Thank you! 😁

**Comment by emeeks** [comment]
<img width="634" alt="screen shot 2018-04-28 at 12 05 03 am" src="https://user-images.githubusercontent.com/495634/39393255-d897ed0a-4a77-11e8-9bfa-757686a15951.png">

Here's an example of viz in tooltip, it's really quite easy you just through another frame into the `tooltipContent`:
https://codepen.io/emeeks/pen/pVNmZW

And here's an example with a static tooltip that has its own tooltips:
https://codepen.io/emeeks/pen/vjywvY

The critical things to recognize here are:
1) You can create any kind of "tooltip" style annotation by sending the `annotations` property a `frame-hover` annotation. That's all I'm doing with this example. You could tie this to a customHoverBehavior or a customClickBehavior in Semiotic or via some other button in your application or whatever you want, just send a properly formatted annotation as part of the annotations array and it will appear in the html annotation layer. In this case, the annotation looks like this:
```
  annotations={[{
   type: "frame-hover",
   D: 4,
   Pts: 30,
   coincidentPoints: [
     { data: {W: 10, Team: "Something Elese" }},
     { data: {W: 5, Team: "Something" }}
   ]                     
}]}
```
Not because it has to but because it follows the structure of the data object I expect in my `tooltipContents` rule. The only thing it has to have is the proper x/y coordinates for your data (in this case, `D` and `Pts` that's why it shows up on the graph where it does).
2) The CSS needs to specify that `pointer-events` are turned on. By default, pointer events are turned off in the annotation layer. You'll see over in the CSS these settings:
```
.tooltip-content {
  pointer-events: all;
```
Along with other styling of the tooltip-content div.

Let me know if you have any problems, it seemed to work fine for me.

Oh and here's an example of a viz in a tooltip in a viz in a tooltip: https://codepen.io/emeeks/pen/NMbVZg

**Comment by ZachHaber** [comment]
Thanks for those, there's still one part of this I'm not sure of. How would I make it so the first layer of tooltips stays open such that someone could interact with it? As with https://codepen.io/emeeks/pen/NMbVZg, but less static. I'd need to be able to interact with all of the tooltips in the same way.
For example, think of the tooltips in visual studio code. When you put the mouse over the tooltip, the tooltip remains in place because there's things you need to interact with on them, and then it disappears the moment you move the mouse off of them.

**Comment by emeeks** [comment]
Here's an example of manually crafting a viz in tooltip and the settings you have to adjust in CSS:
https://codepen.io/emeeks/pen/GdOGZZ?editors=0110

**Comment by ZachHaber** [comment]
https://codepen.io/ZachHaber/pen/VxXQGO?editors=0110
Just thought I'd drop this here. I added timed closing of the tooltips such that it will close automatically in a fairly reasonable way.

**Comment by emeeks** [comment]
I love it! You should put together a more involved example with interesting data because that's always more engrossing. I'm definitely guilty of making examples that demonstrate a feature technically without showing how and why it's a good feature.

**Comment by ZachHaber** [comment]
I'm quite happy you like it! Sadly, I don't really have any data I can make an example using currently.
