### ISSUE TITLE
style mark on interaction

### ISSUE THREAD

**Issue by micahstubbs** [emeeks/semiotic#233]
it would be nice to have a convenient way to style a mark on interaction, for example when the user mouses over or or clicks on that mark.

if this _is_ something that Semiotic supports already, it would be nice to document that 😄 

my use case is changing the `opacity` of a bar on mouseover. 

an example of the styling ability I have in mind is how this vanilla d3 example changes the color of the bar on mouseover:
https://bl.ocks.org/rcrocker13/66a11b84ff86edc61ffb61b3d99cf02a

![bar-color-on-mouseover-1](https://user-images.githubusercontent.com/2119400/40030882-d93d9570-57a1-11e8-9459-48a70f54cbec.gif)

**Comment by emeeks** [comment]
This should be covered in the poorly documented `highlight` annotation type that is shown in the Creating Cross Highlights docs (which should probably also include some mention of simple highlighting):
https://emeeks.github.io/semiotic/#/semiotic/creatingpcrosshighlight

If it doesn't do the right thing or would make more sense otherwise, feel free to suggest.

**Comment by emeeks** [comment]
Gonna close this and assume `highlight` works for you.
