### ISSUE TITLE
I can't update to versions > 1.10.2

### ISSUE THREAD

**Issue by ZachHaber** [emeeks/semiotic#239]
Whenever I try updating semiotic, I get 
![image](https://user-images.githubusercontent.com/19843782/40241259-2e4c4b20-5a80-11e8-8bda-63f6e500ae65.png)
I've tried verifying the npm cache, uninstalling and reinstalling it, updating to version 1.10.3 as well as 1.10.4. Regardless, I get this error. The error only occurs for these two versions currently. I can install 1.10.2 just fine. I know you recently redid a lot of the build bits, so I figure this is probably an issue with that.
Thanks for the support 😃

**Comment by emeeks** [comment]
This must be related to the change in how git repo dependencies are declared in the package.json for Yarn interoperability. What version of Node and NPM are you on?

**Comment by ZachHaber** [comment]
I am using NPM version 6.0.1 and Node version 8.9.4

**Comment by emeeks** [comment]
Looks like some kind of firewall issue?
https://github.com/angular/angular-phonecat/issues/235

Can you tell me if this works:
```
git config --global url."https://".insteadOf git://
```

I think the ultimate fix for this is to publish these forks rather than pointing to the repos.

**Comment by ZachHaber** [comment]
It worked!!! Thank you so much! 🎉 
I wish my attempts to google the problem had led me there, but alas, googling is an art form I have not fully perfected.

**Comment by cvkline** [comment]
Late to the party, but my fix for yarn was to replace the `github:` shortcut for the full URL spec for github repos.  Since the shortcut expands exactly into the URL form under npm, I wouldn't think that was a suspect.

Strong work, Elijah, on finding the root cause here as a firewall issue. And I agree that pointing at github instead of npmjs repos is a bit of an anti-pattern.
