### ISSUE TITLE
Change order of render elements

### ISSUE THREAD

**Issue by emeeks** [emeeks/semiotic#289]
Allow users to set a renderHierarchy property on frames that orders the rendered elements so people can determine whether lines should be drawn above or below points and so on.

**Comment by ZachHaber** [comment]
Would this enable me to make the oLabels render below the data visualization (the main graph)? If so, that would be perfect! 😄 
For reference: I set some graphs to have similar oLabels as 
https://emeeks.github.io/semiotic/#/semiotic/divergingstackedbar
Since I am using ordinalFrames with a lot of different ordinal types and I wanted to make it easier to see which mark belongs to which term. The only issue that I came across with that is that the new row coloring affect the color of the marks.

**Comment by emeeks** [comment]
@ZachHaber This was introduced in 1.13.3 but it is only for the lines, points, areas, summaries, etc. and not for the labels/annotations/axes. That will have to wait for a later compositional system.
