### ISSUE TITLE
XYFrame Area Type heatmap creates extra rows/columns

### ISSUE THREAD

**Issue by emeeks** [emeeks/semiotic#310]
On the right/bottom with changing datasets.

**Comment by jasonk000** [comment]
Specific example below, you can see the 7th row from the bottom , and some of the columns, have 0s for data. These rows are being inserted into the middle of the heatmap. It appears to be something relating to bucketing, since in this case, the values for the columns are integers, and the row in between falls between two integer valued rows.

![image](https://user-images.githubusercontent.com/3196528/44414555-eab4f900-a522-11e8-91c0-ded7de216e14.png)
