### ISSUE TITLE
Bug: Areas for Lines no longer work

### ISSUE THREAD

**Issue by susielu** [emeeks/semiotic#313]
Is it possible to add in an "area" lineType to XYFrame. Previously lines had a top and bottom (along the 0 baseline) so lineType = "line" would allow for an "area" type, this is no longer the case in the latest version. 

If you change lineType in this codePen from "difference" to "line" you see the bug. 

https://codepen.io/emeeks/pen/Qazezb

![image](https://user-images.githubusercontent.com/1449837/44756228-7cea6d80-aade-11e8-9306-d38da8982b6f.png)

**Comment by emeeks** [comment]
Under the hood lines were switched from area lines to regular line lines because of the Chrome bug that shows up with trying to draw a straight line. You can still get area lines via setting the `y1` prop of a `line` lineType or setting `simpleLine` to false.

```
 lineType={{ type: "line", simpleLine: false, y1: () => 0, interpolator: d3.curveLinear }}
```

`simpleLine: false` will draw the area style lines that Semiotic used to have, whereas setting the `y1` prop allows you to draw a filled 0-baseline line like you do with the movies example. Let me know if you're expecting something else.
