### ISSUE TITLE
XYFrame ignore Element provided as matte

### ISSUE THREAD

**Issue by fuocor** [emeeks/semiotic#319]
If I provide an Element to the matte property of the XYFrame it is ignored and the default is used.

the offending code seems to be at line 602 in XYFrame.js
```
   if (currentProps.matte) {
      marginGraphic = (
        <path
          fill="white"
          transform={`translate(${-margin.left},${-margin.top})`}
          d={drawMarginPath({
            margin,
            size: size,
            inset: currentProps.matte.inset
          })}
          className="xyframe-matte"
        />
      )
    }`
```
PS - if the matte is set to false then the lines are not clipped and bleed into the left axis when the xExtent is updated by a minimap.

rich

**Comment by emeeks** [comment]
Oh yeah, that was by design, the matte wasn't meant to be a generic shape but rather a region around the margin area. `foregroundGraphics` and `backgroundGraphics` are more meant for custom graphics but I suppose their problem is that the exist behind and in front of the viz and not semi-in-between like the matte.

So I'll make it render any conforming SVG JSX that's sent. And I'll do one better, I'll also render a function that passes the current margin and size props so your matte can be dynamic in a responsive frame.

**Comment by fuocor** [comment]
Thanks.. the problem I had with the default is the white background not matching my container background and I want to avoid CSS. 
Another problem seems to be the matte position actually being off by a few pixels thereby exposing  lines to the left of the Y-Axis.

**Comment by emeeks** [comment]
In 1.14.2 you can pass JSX SVG or a function with signature `({ size, margin }) => <JSX SVG />`
