### ISSUE TITLE
Default to not check bounding box for axis component

### ISSUE THREAD

**Issue by susielu** [emeeks/semiotic#351]
![image](https://user-images.githubusercontent.com/1449837/48233619-ca9b1600-e36a-11e8-8df9-88211fc61cf7.png)
The axis auto-placement seems to have some performance issues. Would be great if this didn't happen as the default.

**Comment by dgwyer** [comment]
Susie, may I ask if the web page you have displayed in the screenshot is live online? I like the style/formatting. It looks similar to the Semiotic docs but with a different style to the wiki docs here:

https://emeeks.github.io/semiotic/#/

**Comment by susielu** [comment]
@dgwyer I'm in the midst of working on a v2 of the docs site, it isn't up anywhere yet 😅

**Comment by dgwyer** [comment]
Ah, right. That explains it then! :)

Is there a way of being notified when the new docs go live?

Also, a bit off topic I know but, it would be super useful to have full source code available for each example shown in the docs so that you can just copy it and directly drop it in a new JS file (including data, import statements etc.).

**Comment by emeeks** [comment]
In `1.15.9` axes now have a `dynamicLabelPosition` prop that needs to be set to `true` to enable SVG bbox label positioning
