### ISSUE TITLE
Support for polar/radar charts

### ISSUE THREAD

**Issue by benjaminettori** [emeeks/semiotic#380]
Hi

from looking through the documentation, it does not appear you support radar charts (didn't see a way to do this through the axes api). 

Can you confirm this is the case, and if so, whether there are any plans to implement this in the future?

**Comment by emeeks** [comment]
You could make a poor radar plot with OrdinalFrame using `type: point` and `projection: radial` and `connectorType` but I updated it so that it created filled areas to that it's a more true radar plot. I do not plan to introduce a true polar projection into XYFrame. Here's a simple pen using `1.16.5` which was just released:

https://codepen.io/emeeks/pen/bzxNNJ

I'm going to close this but feel free to re-open with any issues you experience or feature requests (or open separate issues).
