### ISSUE TITLE
controlling xAxis divisions and tickLines (XYFrame)

### ISSUE THREAD

**Issue by eesur** [emeeks/semiotic#71]
apologies if I'm  missing something obvious here

I'm unable to work out how to control the `xAxis` division and `tickLines` when using `XYFrame`, not sure how the divisions are calculated?

For example, here's my chart rendered:

<img width="831" alt="screen shot 2017-10-26 at 21 44 41" src="https://user-images.githubusercontent.com/1597761/32076181-fac2d37a-ba96-11e7-94a7-27268e0ad5a3.png">

It has strings passed in for the xAxis:
 `['2010', '2011', '2012', '2013', '2014', '2015', '2016', '2017']`

Not sure how I can stop them being split into 2010.5 etc?

----------------

 I tried to pass in a custom scale (`d3.scalePoint()`) but got build errors for the ticks.

The only way I can get is showing as wanted, is passing in the `tickValues` to the axes:

```
<XYFrame
  ...
  axes={[
    {
      orient: 'left'
    },
    {
      orient: 'bottom',
      tickValues: (d) => d.map(datum => datum.year)
    }
  ]}
/>
```

<img width="834" alt="screen shot 2017-10-26 at 21 47 41" src="https://user-images.githubusercontent.com/1597761/32076289-578bdc96-ba97-11e7-9208-ed1dd7527066.png">

----------------

FYI: my dummy data looks like (it's random generated, so my lines in imgs look different): 

```
[
  {
    "coordinates": [
      {
        "year": "2010",
        "rank": 32
      },
      {
        "year": "2011",
        "rank": 45
      },
      ...
    ]
  }
]
```

----------------
 
any help, pointers on how to control/set the gridlines/tickLines and their divisions would be super appreciated, thanks!

**Comment by emeeks** [comment]
The axis under the hood uses `d3-scale`'s ticks() function, which tries to generate pretty ticks and sometimes screws up like this. The only solution is to calculate or otherwise generate your own ticks and send them to the axis object. In this case, you could send the whole values as an array to the axis `ticks` property.

Another way to deal with this for those reading later is to add the logic to your `tickFormat` property, so that it only renders labels that satisfy a certain test, so in this case you could check to see if the values are whole values and render them if so or, if not, to render an empty string.

Going to close this, feel free to re-open if it doesn't make sense or if there was another problem.
